# Generated by Django 3.1.2 on 2020-11-30 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzashopapp', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveIntegerField(choices=[(1, 'admin'), (2, 'owner'), (3, 'moderator'), (4, 'customer')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
