# Generated by Django 3.1.2 on 2020-11-30 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzashopapp', '0004_client_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_Role',
            new_name='ClientRole',
        ),
    ]
