# Generated by Django 3.1.2 on 2020-11-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0005_auto_20201130_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrole',
            name='user',
        ),
    ]
