# Generated by Django 3.1.2 on 2020-12-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0004_clentrole'),
        ('pizzashopapp', '0006_remove_clientrole_user'),
    ]

    operations = [
    ]
