# Generated by Django 3.1.2 on 2020-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0007_merge_20201202_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClientRole',
        ),
    ]
