# Generated by Django 3.1.2 on 2020-12-02 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzashopapp', '0008_auto_20201202_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testuser', to='auth.user'),
            preserve_default=False,
        ),
    ]
