# Generated by Django 3.1.2 on 2020-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0009_testmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='role',
            field=models.PositiveIntegerField(choices=[(4, 'monitor'), (3, 'customer'), (2, 'onwer'), (1, 'admin')], default=None),
        ),
    ]
