# Generated by Django 3.1.2 on 2020-12-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0010_testmodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='role',
        ),
    ]
